packages:
  - "apps/*"

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": false
  bcrypt: true
  esbuild: true
  msw: true
  prisma: true

catalog:
  "@types/node": ^22.0.0
  typescript: ^5.9.0
  vitest: ^4.0.0
